### ISSUE TITLE
SkipTo doesn't detect h1 in banner landmark

### ISSUE THREAD

**Issue by kokimo1** [paypal/skipto#101] opened 2021-09-22 19:21 UTC
Hello, long time developer, first time pull requestor here. 

We have an h1 heading element on our site for the site name (see [https://red.uic.edu](https://red.uic.edu)), but SkipTo doesn't detect it because it lives in the header. H1 heading requirements extend to both main and banner landmarks, so I believe including the banner role would be a good addition/enhancement for SkipTo. 

I have a fix ready, but rather than implementing it on just our end I thought I'd send it upstream for review. I don't have access rights to push a feature branch to the repo, so may I be added as a collaborator?

**Comment by brianteeman** [comment] 2021-09-22 20:15
Please just submit a pull request instead of a feature branch

**Comment by kokimo1** [comment] 2021-09-22 20:43
Hi, sorry for the noob question, but I come from a Gitlab shop and I'm still getting my bearings in Github. Do you want me to commit to main and create the PR from main into master?

**Comment by brianteeman** [comment] 2021-09-22 20:47
https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

**Comment by brianteeman** [comment] 2021-09-22 20:49
I'm wondering if the problem is because the h1 is inside a link which is the same as #35 by @jongund

**Comment by kokimo1** [comment] 2021-09-22 21:20
Ah, I have to fork and PR from there, got it. I read the Github documentation on pulls requests but missed the forking info below it. 

I checked Jon's example, and the AHS site is actually the opposite: it has the anchor inside the h1. I switched them on my site locally so it goes h1 then anchor, but it's still not seeing the h1. Aight, I'll fork and PR the correct way. Thanks for the info, man!

**Comment by brianteeman** [comment] 2021-09-22 21:30
Great - I will keep my eye out for it

**Comment by jongund** [comment] 2021-09-22 21:50
Best practices are for H1 to be at the start of the main content.  You can have an H1 in the banner, but is not very useful for navigation, since keyboard navigation already starts at the beginning of the page.
Remember skip to is about users navigation to important places on the page.
The default configuration for SkipTo is to only include H1 and H2 headings found in the main content.


The landmark and heading selectors can be configured, see configuration options, but again think of what you want in the menu from the keyboard users perspective.

See the section "CSS Selectors for identifying Landmarks and Headings" in the documentation:
https://github.com/paypal/skipto/blob/main/README.md

**Comment by brianteeman** [comment] 2021-09-27 13:29
Closed as discusses in #102

**Closed by brianteeman** 2021-09-27 13:29 UTC
